services:
  - type: web
    name: sbs-monitor
    env: node
    plan: free
    branch: main
    buildCommand: |
      npm install
      npx playwright install --with-deps
    startCommand: node index.js
    autoDeploy: true